#!/usr/bin/env node
const { once } = require('node:events');
const fs = require('fs');
const argv = process.argv.slice(2).flat();
const fileStream = fs.createReadStream(argv[0]);
const lineReader = require('readline').createInterface({
    input: fileStream,
    crlfDelay: Infinity
});

var lineNum = 0;
var colsArr = [];
var jsonArr = [];

lineReader.on('line', (line) => {
    if (lineNum == 0) {
        colsArr = line.split(',');
        lineNum++;
        return;
    }
    const obj = {};
    line.split(',').forEach((v, i) => {
        if (v.length > 0) { obj[colsArr[i]] = v; }
    });
    if (Object.keys(obj).length > 0) { jsonArr.push(obj); }
    lineNum++;
});

(
    async function () {
        await once(lineReader, 'close');
        if (argv[1]) {
            fs.writeFileSync(argv[1], JSON.stringify(jsonArr, null, 2), err => {
                if (err) {
                    console.error(err);
                }
            });
            fs.appendFileSync(argv[1], "\n", err => {
                if (err) {
                    console.error(err);
                }
            });
        } else {
            console.log(JSON.stringify(jsonArr, null, 2));
        }
    }
)();
