#!/usr/bin/env node
const { once } = require('node:events');
const fileStream = require('fs').createReadStream(process.argv.slice(2).flat()[0]);
const lineReader = require('readline').createInterface({
    input: fileStream,
    crlfDelay: Infinity
});

var lineNum = 0;
var colsArr = [];
var jsonArr = [];

lineReader.on('line', (line) => {
    if (lineNum == 0) {
        colsArr = line.split(',');
        lineNum++;
        return;
    }
    const obj = {};
    line.split(',').forEach((v, i) => {
        if (v.length > 0) { obj[colsArr[i]] = v; }
    });
    jsonArr.push(obj);
    lineNum++;
});

(
    async function () {
        await once(lineReader, 'close');
        console.log(JSON.stringify(jsonArr, null, 2));
    }
)();

